DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS city;
DROP TABLE IF EXISTS company;
DROP TABLE IF EXISTS route;
DROP TABLE IF EXISTS discount;

CREATE TABLE city (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL
);

CREATE TABLE company (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL
);

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  surname TEXT NOT NULL,
  age INTEGER NOT NULL,
  budget FLOAT NOT NULL,
  discount_diff FLOAT NOT NULL,
  city_id INTEGER NOT NULL,
  company_id INTEGER NOT NULL,
  FOREIGN KEY (city_id) REFERENCES city (id),
  FOREIGN KEY (company_id) REFERENCES company (id)
);

CREATE TABLE route (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  route_date DATE NOT NULL DEFAULT CURRENT_DATE,
  total_km FLOAT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id)
);

CREATE TABLE discount (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  img TEXT NOT NULL,
  discount_rate FLOAT NOT NULL
);